import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import OurValues from "@/components/ourValues";
import Services from "@/components/services";
import Testimonials from "@/components/testimonials";
import ContactUs from "@/components/contact";
import Footer from "@/components/footer";
import HeroSection from "@/components/hero";
import OurApproach from "@/components/ourApproach";
// import HeroSection from "@/components/heroSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Sai Consultancy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="keywords"
          content="sai consultancy, consultancy, sai consultancy services"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <OurValues />
      <Services />
      <Testimonials />
      <OurApproach />
      <ContactUs />
      <Footer />
    </>
  );
}
